openapi: "3.0.0"
info:
  version: Beta
  title: Refond App API
  description: ...
  license:
    name: MIT
  contact:
    name: API Support
    url: http://www.example.com/support
    email: refond-help@mit.edu
servers:
  - url: localhost:3000
tags:
  - name: credentials
    # description: Everything about account credentials
    # externalDocs:
    #   description: Find out more
    #   url: http://swagger.io
  - name: story
  #   description: Access to Petstore orders
  - name: profile
paths:
  /credential:
    $ref: "./resources/credential.yaml"
  /story:
    $ref: "./resources/story_card.yaml"
  /story/list:
    $ref: "./resources/story_list.yaml"
  /story/interaction:
    $ref: "./resources/interaction.yaml"
  /profile/udpate/info:
    $ref: "./resources/profile_update_info.yaml"
  /profile/update/picture:
    $ref: "./resources/profile_update_picture.yaml"
  /profile/picture:
    $ref: "./resources/profile_get_picture.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"